name: test-associative-property

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: generate files
        run: python generate_files.py

      - name: init CSV
        run: echo "repetitions,op1,op2,result" > results_associativity.csv

      - name: show generated files content
        run: |
          for f in generated_property_check_*.py; do
            echo "================= $f ================="
            cat "$f"
            echo
          done

      - name: run generated tests
        run: |
          for f in generated_property_check_*.py; do
            python "$f"
          done
